# fly.toml app configuration file generated for vinyl-collection-backend on 2026-02-06T12:59:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vinyl-collection-backend'
primary_region = 'fra'

[build]
  dockerfile = 'functions/Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
